// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfLRqBe3TFxk__T_wWy5BW5oJ2N0PNQJk',
    appId: '1:236093632018:web:d4af6a89c651f55de432cb',
    messagingSenderId: '236093632018',
    projectId: 'wanbook-6448e',
    authDomain: 'wanbook-6448e.firebaseapp.com',
    storageBucket: 'wanbook-6448e.firebasestorage.app',
    measurementId: 'G-633705CNVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoY32s7xjmkc9Ya454WmNxmtF3puB54XE',
    appId: '1:236093632018:android:5bbc83c6f8bf3a18e432cb',
    messagingSenderId: '236093632018',
    projectId: 'wanbook-6448e',
    storageBucket: 'wanbook-6448e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA92kjN0KuirlpFs-XgYN4MkxXDHv4cvDI',
    appId: '1:236093632018:ios:3a9bca4527165acae432cb',
    messagingSenderId: '236093632018',
    projectId: 'wanbook-6448e',
    storageBucket: 'wanbook-6448e.firebasestorage.app',
    iosBundleId: 'com.example.wanbook',
  );
}
